### PR TITLE
Verify Target Group attributes

### PR DESCRIPTION
**Pull request by akrito**
Please don't rubber-stamp ;-) as I suspect there's a simpler way to traverse the APIs to get to the attributes.

### CODE REVIEW

**Review by sharms — COMMENTED** [review]
It looks like we need to start a session, get the load balancers, get the target groups, and then describe the attributes and that seems pretty normal unless we had those values prior to running the test.  LGTM but I will leave it for a 2nd pair of eyes

**Comment by akrito** [comment]
I could skip right to the "get the target groups" step by creating a tag-based Resource Group, constrain it to the Target Group type, and filter by the tags "Name: gitlab-nginx" and "elbv2.k8s.aws/cluster: $cluster_name". But we don't currently have any Resource Groups defined in login-tooling, so maybe it's not worth adding another thing to manage just to make test code shorter.

**Comment by akrito** [comment]
No, @akrito, that's not a good idea. There's no guarantee that the tagged resources in AWS are current, and not detritus from previous cluster state. You need to follow the chain all the way from querying k8s for the ingresses.

**Review by timothy-spencer — APPROVED** [review]
This looks good to me too, and I can't think of any more clever ways to do this either.  :-)

Thank you for the comments, they help me understand what you are doing!

**Pull request merged**
